### ISSUE TITLE
Bug Report: Decorate File/Folder Not Working

### ISSUE THREAD

**Issue by HikingDev** [luisfontes19/vscode-swissknife#19]
**Description**:

The Swissknife extension is not functioning when attempting to decorate a file or folder in the Explorer. No changes occur upon attempting to use this feature. The error happens regardless if a file or folder are selected. It always seems to append a '/' to the path. 

**Steps to Reproduce:**

1. Open Visual Studio Code.
2. Navigate to a file or folder in the Explorer.
3. Attempt to use the Swissknife extension to decorate the selected item.
4. Observe that no decoration is applied.

**Expected Behavior:**

The selected file or folder should be decorated as specified by the Swissknife extension.

**Actual Behavior:**

No decoration is applied to the selected file or folder.

**Extension Version:**
1.8.1

**Error Log:**

`2024-06-26 10:55:05.635 [error] Error: ENOENT: no such file or directory, lstat '/c:/tmp/cert.pem.crt'
    at lstatSync (node:fs:1656:3)
    at Object.t.lstatSync (node:electron/js2c/node_init:2:4191)
    at FileDecorator.decorate (path_to_extension\out\extension.js:105851:27)
    at path_to_extension\out\extension.js:105559:98
    at h (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:200476)
    at h.$executeContributedCommand (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:201336)
    at E.S (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5970)
    at E.Q (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5736)
    at E.M (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4762)
    at E.L (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3589)
    at n.value (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2282)
    at l.y (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
    at l.fire (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
    at s.fire (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
    at n.value (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8481)
    at l.y (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:664)
    at l.fire (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:881)
    at s.fire (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14502)
    at MessagePortMain.<anonymous> (path_to_vscode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6631)
    at MessagePortMain.emit (node:events:514:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
`

**System Info:**

Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045**

**Comment by luisfontes19** [comment]
Hello @HikingDev 

Im sorry for the late reply, I haven't been working on the extension for a while and email notifications got last among the spam 😅

This seems to be a bug specifically for windows systems. Will roll out a fix in a few hours

**Comment by luisfontes19** [comment]
This is fixed in 1.8.8. 

This one if for me 🏆: Longest time to fix such a simple bug 🥲 Sorry for that
